import pygame


WIDTH = 1280
HEIGHT = WIDTH * (4 / 9)

FRAME_RATE = 60

# FIELD

FIELD_YARDS = 120
FIELD_ASPECT_RATIO = 4 / 9
FIELD_WIDTH = WIDTH
FIELD_HEIGHT = FIELD_WIDTH * FIELD_ASPECT_RATIO
FIELD_CENTER = pygame.Vector2(FIELD_WIDTH / 2, FIELD_HEIGHT / 2)
YARD_LENGTH = FIELD_WIDTH / FIELD_YARDS
FIELD_HASH_LENGTH = YARD_LENGTH * (2 / 3)
FIELD_HASH_DISTANCE = YARD_LENGTH * 6.16  # NFL standard 6.16
GOAL_POST_WIDTH = YARD_LENGTH * 6.16

# ENTITY SIZES

PLAYER_RADIUS = 6
BALL_RADIUS = 3
HALO_RADIUS = PLAYER_RADIUS * 1.5

# COLLISION PARAMETERS

COLLISION_DISTANCE = PLAYER_RADIUS * 2
COLLISION_NUDGE = 1
COLLISION_REPULSION_FACTOR = 1

# MOVEMENT PARAMETERS

ACCELERATION_RATE = 0.4
DECELERATION_RATE = 0.85

# Approximate max player speed as 4.2 seconds to run 40 yards
FORTY_YARDS = 40 * YARD_LENGTH
FASTEST_40_TIME = 4.2
n = int(FASTEST_40_TIME * FRAME_RATE)
if ACCELERATION_RATE == 0:
    PLAYER_MAX_SPEED = FORTY_YARDS / FRAME_RATE / FASTEST_40_TIME
else:
    denom = n - (1 - (1 - ACCELERATION_RATE) ** n) / ACCELERATION_RATE
    PLAYER_MAX_SPEED = FORTY_YARDS / denom

# THROWING PARAMETERS

THROW_MAX_YARDS = 80
# Approx 70 mph for elite QB throw power
THROW_SPEED = (35 * YARD_LENGTH) / FRAME_RATE
# Minimum frames for a short throw
THROW_MIN_FRAMES = 10
# Higher value = less accurate
THROW_DEVIATION_FACTOR = 0.25
PERFECT_THROWING = False
# Minimum arc height
THROW_MIN_ARC = YARD_LENGTH * 2.5
# Higher value = lower arc
THROW_ARC_DIVISOR = 6

# CATCHING PARAMETERS

# Max height the ball can be caught at (2.33 = approx 7 feet)
CATCH_MAX_HEIGHT = YARD_LENGTH * 2.33
# How close (in pixels) the ball must be to the player to be catchable
CATCH_RADIUS = PLAYER_RADIUS * 2
# If True, catching stat has no effect
PERFECT_CATCHING = False
